import { LedgerEntry, LedgerEntryStatus, LedgerEntryType } from "src/types";

export const mockPendingDepositEntries: LedgerEntry[] = [
  {
    id: 'LEDGER_1640995200_student001',
    theme: '동아리 활동비',
    amount: 50000,
    entryType: LedgerEntryType.DEPOSIT,
    status: LedgerEntryStatus.APPROVED,
    approvedBy: '',
    createdBy: 'student001',
    creatorName: '김철수',
    timestamp: 1640995200,
    description: '동아리 회비 납부',
    approvals: [],
    rejections: [],
    documentURL: 'https://s3.example.com/deposit_receipt001.pdf',
  },
  {
    id: 'LEDGER_1640996000_student002',
    theme: '행사비',
    amount: 120000,
    entryType: LedgerEntryType.DEPOSIT,
    status: LedgerEntryStatus.PENDING,
    approvedBy: '',
    createdBy: 'student002',
    creatorName: '이영희',
    timestamp: 1640996000,
    description: '축제 후원금',
    approvals: [],
    rejections: [],
    documentURL: 'https://s3.example.com/deposit_receipt002.pdf',
  },
  {
    id: 'LEDGER_1640996800_student003',
    theme: '장학금',
    amount: 300000,
    entryType: LedgerEntryType.DEPOSIT,
    status: LedgerEntryStatus.PENDING,
    approvedBy: '',
    createdBy: 'student003',
    creatorName: '박민수',
    timestamp: 1640996800,
    description: '학업우수 장학금 기부',
    approvals: [],
    rejections: [],
    documentURL: 'https://s3.example.com/deposit_receipt003.pdf',
  },
  {
    id: 'LEDGER_1640997600_student004',
    theme: '복리후생비',
    amount: 80000,
    entryType: LedgerEntryType.DEPOSIT,
    status: LedgerEntryStatus.PENDING,
    approvedBy: '',
    createdBy: 'student004',
    creatorName: '정수진',
    timestamp: 1640997600,
    description: '학생 간식비 후원',
    approvals: [],
    rejections: [],
    documentURL: 'https://s3.example.com/deposit_receipt004.pdf',
  },
  {
    id: 'LEDGER_1640998400_student005',
    theme: '시설비',
    amount: 200000,
    entryType: LedgerEntryType.DEPOSIT,
    status: LedgerEntryStatus.PENDING,
    approvedBy: '',
    createdBy: 'student005',
    creatorName: '한민석',
    timestamp: 1640998400,
    description: '학습실 개선 기금',
    approvals: [],
    rejections: [],
    documentURL: 'https://s3.example.com/deposit_receipt005.pdf',
  },
  {
    id: 'LEDGER_1640999200_student006',
    theme: '동아리 활동비',
    amount: 75000,
    entryType: LedgerEntryType.DEPOSIT,
    status: LedgerEntryStatus.PENDING,
    approvedBy: '',
    createdBy: 'student006',
    creatorName: '오서연',
    timestamp: 1640999200,
    description: '밴드 동아리 악기 구입비',
    approvals: [],
    rejections: [],
    documentURL: 'https://s3.example.com/deposit_receipt006.pdf',
  },
  {
    id: 'LEDGER_1641000000_student007',
    theme: '행사비',
    amount: 150000,
    entryType: LedgerEntryType.DEPOSIT,
    status: LedgerEntryStatus.PENDING,
    approvedBy: '',
    createdBy: 'student007',
    creatorName: '송태희',
    timestamp: 1641000000,
    description: '졸업식 기념품 제작비',
    approvals: [],
    rejections: [],
    documentURL: 'https://s3.example.com/deposit_receipt007.pdf',
  },
  {
    id: 'LEDGER_1641000800_student008',
    theme: '교육비',
    amount: 100000,
    entryType: LedgerEntryType.DEPOSIT,
    status: LedgerEntryStatus.PENDING,
    approvedBy: '',
    createdBy: 'student008',
    creatorName: '최지원',
    timestamp: 1641000800,
    description: '프로그래밍 강의 수강료',
    approvals: [],
    rejections: [],
    documentURL: 'https://s3.example.com/deposit_receipt008.pdf',
  },
];