apiVersion: v1
kind: Service
metadata:
  name: ca-student
  labels:
    app: ca-student
spec:
  type: ClusterIP
  selector:
    app: ca-student
  ports:
    - protocol: TCP
      targetPort: 7054
      port: 7054