apiVersion: v1
kind: Service
metadata:
  name: ca-student-council
  labels:
    app: ca-student-council
spec:
  type: ClusterIP
  selector:
    app: ca-student-council
  ports:
    - protocol: TCP
      targetPort: 8054
      port: 8054