--- #---------------- Chaincode Service ---------------------
apiVersion: v1
kind: Service
metadata:
  name: organization-student
  labels:
    app: organization-student
spec:
  ports:
    - name: grpc
      port: 7052
      targetPort: 7052
  selector:
    app: chaincode-organization-student
