--- #---------------- Chaincode Service ---------------------
apiVersion: v1
kind: Service
metadata:
  name: organization-student-council
  labels:
    app: organization-student-council
spec:
  ports:
    - name: grpc
      port: 7052
      targetPort: 7052
  selector:
    app: chaincode-organization-student-council
