apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv
spec:
  storageClassName: local-path
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/lib/minikube/hostpath-provisioner  # 로컬 스토리지 경로로 변경